 services:
   api-students:
     build: ./api-students
     ports:
       - 8000:8000
   websimple:
     build: ./websimple
     ports:
       - 8080:80
   webplantilla:
     build: ./webplantilla
     ports:
       - 9000:9000
